# Render.com deployment config for backend
version: 2
services:
  - type: web
    name: ssb-connect-backend
    env: node
    region: oregon
    plan: free
    rootDir: backend
    buildCommand: npm install && npm run build
    startCommand: npm start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
    # Add your other env vars in Render dashboard:
    # MONGODB_URI, JWT_SECRET, MAILGUN_API_KEY, etc.